"""add adjuvant type

Revision ID: 2b3b9781b17d
Revises: c612d6b34789
Create Date: 2026-09-21 08:11:24.285321
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = '2b3b9781b17d'
down_revision = 'c612d6b34789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('adjuvant_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'adjuvant_type')
    # ### end Alembic commands ###
