"""store document text

Revision ID: 2f15f2b21c85
Revises: 2b3b9781b17d
Create Date: 2026-09-21 08:25:08.412030
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = '2f15f2b21c85'
down_revision = '2b3b9781b17d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_files', sa.Column('storage_mode', sa.String(length=16), nullable=False))
    op.add_column('source_files', sa.Column('origin_url', sa.Text(), nullable=True))
    op.add_column('source_files', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('source_files', sa.Column('text_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_files', 'text_bytes')
    op.drop_column('source_files', 'extracted_text')
    op.drop_column('source_files', 'origin_url')
    op.drop_column('source_files', 'storage_mode')
    # ### end Alembic commands ###
