"""initial schema

Revision ID: c612d6b34789
Revises: 
Create Date: 2026-09-21 07:28:41.206614
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = 'c612d6b34789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('cas_number', sa.String(length=32), nullable=True),
    sa.Column('chemical_class', sa.String(length=120), nullable=True),
    sa.Column('pesticide_type', sa.String(length=64), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('groundwater', sa.Text(), nullable=True),
    sa.Column('surface_water', sa.Text(), nullable=True),
    sa.Column('persistence', sa.Text(), nullable=True),
    sa.Column('ecological', sa.Text(), nullable=True),
    sa.Column('human_health', sa.Text(), nullable=True),
    sa.Column('is_california_restricted', sa.Boolean(), nullable=False),
    sa.Column('is_watchlisted', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_ingredient_slug')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('rate_per_minute', sa.Integer(), nullable=True),
    sa.Column('watermark_seed', sa.String(length=32), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash', name='uq_api_key_hash')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('chemical_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=160), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('is_regulatory', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flag_subject', 'chemical_flags', ['subject_type', 'subject_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_key', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=64), nullable=True),
    sa.Column('dpr_license', sa.String(length=32), nullable=True),
    sa.Column('license_status', sa.String(length=48), nullable=True),
    sa.Column('license_expiration', sa.Date(), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('contact_review_state', sa.String(length=24), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_company_slug')
    )
    op.create_index('ix_company_key', 'companies', ['name_key'], unique=False)
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('fips', sa.String(length=8), nullable=True),
    sa.Column('ag_district', sa.String(length=8), nullable=True),
    sa.Column('ag_department_name', sa.String(length=160), nullable=True),
    sa.Column('ag_department_email', sa.String(length=160), nullable=True),
    sa.Column('ag_department_phone', sa.String(length=40), nullable=True),
    sa.Column('default_meridian', sa.String(length=1), nullable=False),
    sa.Column('default_township_dir', sa.String(length=1), nullable=False),
    sa.Column('default_range_dir', sa.String(length=1), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cpra_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('watermark', sa.Date(), nullable=True),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('files_seen', sa.Integer(), nullable=False),
    sa.Column('files_ingested', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('files_total', sa.Integer(), nullable=False),
    sa.Column('files_failed', sa.Integer(), nullable=False),
    sa.Column('records_extracted', sa.Integer(), nullable=False),
    sa.Column('clusters_created', sa.Integer(), nullable=False),
    sa.Column('ready_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_epa_reg_no', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('registrant', sa.String(length=255), nullable=True),
    sa.Column('formulation', sa.String(length=64), nullable=True),
    sa.Column('signal_word', sa.String(length=32), nullable=True),
    sa.Column('density_lb_per_gallon', sa.Float(), nullable=True),
    sa.Column('is_adjuvant', sa.Boolean(), nullable=False),
    sa.Column('federal_restricted_use', sa.Boolean(), nullable=True),
    sa.Column('california_restricted', sa.Boolean(), nullable=True),
    sa.Column('verification', sa.String(length=16), nullable=False),
    sa.Column('label_url', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_epa_reg_no', name='uq_product_reg')
    )
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('seen_in', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'alias', name='uq_company_alias')
    )
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('apn', sa.String(length=48), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_key', sa.String(length=255), nullable=True),
    sa.Column('situs_address', sa.String(length=255), nullable=True),
    sa.Column('acreage', sa.Float(), nullable=True),
    sa.Column('use_code', sa.String(length=64), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county_id', 'apn', name='uq_parcel_county_apn')
    )
    op.create_index('ix_parcel_owner_key', 'parcels', ['owner_key'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('name_key', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('given_name', sa.String(length=80), nullable=True),
    sa.Column('family_name', sa.String(length=80), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=160), nullable=True),
    sa.Column('business_phone', sa.String(length=40), nullable=True),
    sa.Column('business_email', sa.String(length=160), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('photo_source', sa.Text(), nullable=True),
    sa.Column('contact_review_state', sa.String(length=24), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_person_slug')
    )
    op.create_index('ix_person_key', 'people', ['name_key'], unique=False)
    op.create_table('plss_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mtrs', sa.String(length=16), nullable=False),
    sa.Column('meridian', sa.String(length=1), nullable=False),
    sa.Column('township', sa.Integer(), nullable=False),
    sa.Column('township_dir', sa.String(length=1), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('range_dir', sa.String(length=1), nullable=False),
    sa.Column('section', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mtrs', name='uq_plss_mtrs')
    )
    op.create_table('product_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['active_ingredients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'ingredient_id', name='uq_product_ingredient')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('landowner_name', sa.String(length=255), nullable=True),
    sa.Column('filed_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', name='uq_project_identifier')
    )
    op.create_table('review_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_state', 'review_items', ['state', 'reason'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('profile', sa.String(length=64), nullable=True),
    sa.Column('document_kind', sa.String(length=32), nullable=True),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('cpra_agency', sa.String(length=255), nullable=True),
    sa.Column('cpra_request_number', sa.String(length=64), nullable=True),
    sa.Column('cpra_production', sa.String(length=64), nullable=True),
    sa.Column('inquisitor_source_id', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_state', sa.String(length=32), nullable=False),
    sa.Column('processing_notes', sa.JSON(), nullable=True),
    sa.Column('used_ocr', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='uq_source_sha256')
    )
    op.create_table('application_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_basis', sa.String(length=160), nullable=True),
    sa.Column('title_override', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_key', sa.String(length=255), nullable=True),
    sa.Column('landowner_company_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('total_acres', sa.Float(), nullable=True),
    sa.Column('acreage_is_partial', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('is_mixed_method', sa.Boolean(), nullable=False),
    sa.Column('is_planned', sa.Boolean(), nullable=False),
    sa.Column('site_category', sa.String(length=32), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('review_reasons', sa.JSON(), nullable=True),
    sa.Column('scoring', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['landowner_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_cluster_slug')
    )
    op.create_index('ix_cluster_dates', 'application_clusters', ['date_start', 'date_end'], unique=False)
    op.create_index('ix_cluster_status', 'application_clusters', ['status'], unique=False)
    op.create_table('fact_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=48), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fact_entity', 'fact_sources', ['entity_type', 'entity_id', 'field_name'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('license_type', sa.String(length=24), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_type', 'number', name='uq_license_type_number')
    )
    op.create_table('permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_number', sa.String(length=48), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('operator_key', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.String(length=48), nullable=True),
    sa.Column('agent_name', sa.String(length=160), nullable=True),
    sa.Column('applicant_name', sa.String(length=160), nullable=True),
    sa.Column('applicant_title', sa.String(length=255), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('permit_duration', sa.String(length=64), nullable=True),
    sa.Column('type_of_use', sa.String(length=64), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_number', name='uq_permit_number')
    )
    op.create_table('application_parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.Integer(), nullable=False),
    sa.Column('match_basis', sa.String(length=160), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('owner_match_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['application_clusters.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'parcel_id', name='uq_cluster_parcel')
    )
    op.create_table('application_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['application_clusters.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'role', 'company_id', 'person_id', name='uq_cluster_party')
    )
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('basemap_attribution', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['application_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permit_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('license_number', sa.String(length=32), nullable=True),
    sa.Column('license_expiration', sa.Date(), nullable=True),
    sa.Column('contact_type', sa.String(length=64), nullable=True),
    sa.Column('is_business', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permit_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('pests', sa.String(length=120), nullable=True),
    sa.Column('form', sa.String(length=64), nullable=True),
    sa.Column('methods', sa.String(length=64), nullable=True),
    sa.Column('applicators', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permit_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=True),
    sa.Column('mtrs', sa.String(length=16), nullable=True),
    sa.Column('mtrs_text', sa.String(length=32), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=8), nullable=True),
    sa.Column('commodity', sa.String(length=120), nullable=True),
    sa.Column('commodity_code', sa.String(length=16), nullable=True),
    sa.Column('permitted_acreage', sa.Float(), nullable=True),
    sa.Column('permitted_materials', sa.JSON(), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permit_site_mtrs', 'permit_sites', ['mtrs'], unique=False)
    op.create_table('pur_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('record_kind', sa.String(length=24), nullable=False),
    sa.Column('document_number', sa.String(length=48), nullable=True),
    sa.Column('permit_number', sa.String(length=48), nullable=True),
    sa.Column('permit_id', sa.Integer(), nullable=True),
    sa.Column('site_district', sa.String(length=8), nullable=True),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('operator_key', sa.String(length=255), nullable=True),
    sa.Column('applicator_name', sa.String(length=255), nullable=True),
    sa.Column('applicator_key', sa.String(length=255), nullable=True),
    sa.Column('applicator_license', sa.String(length=32), nullable=True),
    sa.Column('applicator_license_type', sa.String(length=16), nullable=True),
    sa.Column('applicator_address', sa.Text(), nullable=True),
    sa.Column('pca_name', sa.String(length=255), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('site_id', sa.String(length=32), nullable=True),
    sa.Column('mtrs', sa.String(length=16), nullable=True),
    sa.Column('plss_section_id', sa.Integer(), nullable=True),
    sa.Column('site_decode_method', sa.String(length=48), nullable=True),
    sa.Column('site_confidence', sa.String(length=16), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('method_raw', sa.String(length=64), nullable=True),
    sa.Column('commodity', sa.String(length=120), nullable=True),
    sa.Column('commodity_code', sa.String(length=16), nullable=True),
    sa.Column('site_category', sa.String(length=32), nullable=True),
    sa.Column('site_category_confidence', sa.String(length=16), nullable=True),
    sa.Column('planted_amount', sa.Float(), nullable=True),
    sa.Column('planted_units', sa.String(length=24), nullable=True),
    sa.Column('treated_amount', sa.Float(), nullable=True),
    sa.Column('treated_units', sa.String(length=24), nullable=True),
    sa.Column('submittal_status', sa.String(length=48), nullable=True),
    sa.Column('school_notification', sa.String(length=48), nullable=True),
    sa.Column('fulfilled_by_record_id', sa.Integer(), nullable=True),
    sa.Column('in_coverage', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_by_record_id'], ['pur_records.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.ForeignKeyConstraint(['plss_section_id'], ['plss_sections.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'document_number', 'site_id', 'date_start', name='uq_pur_record_identity')
    )
    op.create_index('ix_pur_dates', 'pur_records', ['date_start', 'date_end'], unique=False)
    op.create_index('ix_pur_mtrs', 'pur_records', ['mtrs'], unique=False)
    op.create_index('ix_pur_operator_key', 'pur_records', ['operator_key'], unique=False)
    op.create_table('application_cluster_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['application_clusters.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['pur_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'record_id', name='uq_cluster_record')
    )
    op.create_table('pur_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('epa_reg_no', sa.String(length=48), nullable=True),
    sa.Column('base_epa_reg_no', sa.String(length=48), nullable=True),
    sa.Column('distributor_suffix', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('quantity_units', sa.String(length=24), nullable=True),
    sa.Column('treated_amount', sa.Float(), nullable=True),
    sa.Column('treated_units', sa.String(length=24), nullable=True),
    sa.Column('registration_expired', sa.Boolean(), nullable=True),
    sa.Column('gallons', sa.Float(), nullable=True),
    sa.Column('pounds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['pur_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pur_product_reg', 'pur_products', ['base_epa_reg_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pur_product_reg', table_name='pur_products')
    op.drop_table('pur_products')
    op.drop_table('application_cluster_records')
    op.drop_index('ix_pur_operator_key', table_name='pur_records')
    op.drop_index('ix_pur_mtrs', table_name='pur_records')
    op.drop_index('ix_pur_dates', table_name='pur_records')
    op.drop_table('pur_records')
    op.drop_index('ix_permit_site_mtrs', table_name='permit_sites')
    op.drop_table('permit_sites')
    op.drop_table('permit_materials')
    op.drop_table('permit_contacts')
    op.drop_table('maps')
    op.drop_table('application_parties')
    op.drop_table('application_parcels')
    op.drop_table('permits')
    op.drop_table('licenses')
    op.drop_index('ix_fact_entity', table_name='fact_sources')
    op.drop_table('fact_sources')
    op.drop_index('ix_cluster_status', table_name='application_clusters')
    op.drop_index('ix_cluster_dates', table_name='application_clusters')
    op.drop_table('application_clusters')
    op.drop_table('source_files')
    op.drop_index('ix_review_state', table_name='review_items')
    op.drop_table('review_items')
    op.drop_table('projects')
    op.drop_table('product_ingredients')
    op.drop_table('plss_sections')
    op.drop_index('ix_person_key', table_name='people')
    op.drop_table('people')
    op.drop_index('ix_parcel_owner_key', table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('company_aliases')
    op.drop_table('products')
    op.drop_table('import_batches')
    op.drop_table('cpra_sync_runs')
    op.drop_table('counties')
    op.drop_index('ix_company_key', table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_flag_subject', table_name='chemical_flags')
    op.drop_table('chemical_flags')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('api_keys')
    op.drop_table('active_ingredients')
    # ### end Alembic commands ###
